#;**********************************************************************;
# SPDX-License-Identifier: Apache-2.0
#
# Copyright (c) 2025, Siemens AG
#
#;**********************************************************************;

name: CI
on: 
  [workflow_dispatch, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libcmocka-dev meson ninja-build build-essential libssl-dev cmake pkg-config git valgrind
      - name: Build
        run: |
          meson setup build --werror
          ninja -C build
      - name: Test
        run: |
          ninja -C build test
      - name: Valgrind
        run: |
          ninja -C build gta_framework_memcheck